spring.application.name=women-safety

server.port=8082

spring.datasource.url=jdbc:postgresql://neondb_owner:npg_ICMrGEUkY50t@ep-blue-pine-b4f1v006-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ICMrGEUkY50t
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=women-safety-secret-key-change-this-in-production
jwt.expiration=86400000

twilio.account-sid=AC6bb84822f96e8da7ee85f3e9795d1314
twilio.auth-token=48b2433dc89f5db8023ea1f30c36f836
twilio.phone-number=+16269013781